# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: college
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
